module.exports = [
  {
    title: "Апать (от англ. Up – вверх)",
    text: "подниматься в звании или улучшать что-то",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Байтить ",
    text:
      "изначально копировать стиль у граффитистов. В геймерской среде – заманивать в ловушку",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Видосы",
    text: "видеоролики",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Войс",
    text: "Аудиосообщение в мессенджере",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Вписка",
    text:
      "домашняя вечеринка, чаще всего с ночевкой. Изначально просто жилье, где можно временно остановиться",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Выпилиться",
    text: "Уйти из какой-либо сферы. Также совершить самоубийство",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Гамать",
    text: "Играть во что-либо (например компьюетерные игры)",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Гиг",
    text: "Концерт музыкальной группы",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Вброс",
    text: "Публикация скандальной и зачастую непроверенной информации",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Донатить",
    text: "Жертвовать деньги или в целом оказывать материальную помощь",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Запилить",
    text: "Сделать что-либо",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Зашквар",
    text: "Недостойный поступок или порочащее действие",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Инфасотка",
    text: "Полностью проверенная и достоверная информация",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "К(k)",
    text: "Одна тысяча. 2к19 - 2019",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Катка",
    text: "Игра, матч, поединок",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Кек",
    text: "Короткий, чаще недобрый смешок",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Лойс",
    text: "то же, что и лайк",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Майнить (от англ. mining – добыча полезных ископаемых)",
    text: "зарабатывать в системах криптовалютных платформ",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Мемасы",
    text: "Интернет мемы",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Мерч (от англ. merchandise – товар)",
    text:
      "одежда и сувениры с символикой популярных музыкальных групп и других коммерческих проектов (игр, фильмов и т. д.)",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Нерф",
    text: "Уменьшение показателей чего-либо",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Нуб",
    text: "новичок в геймерской среде, или, в целом, в каком-либо сегменте",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Очешуенно",
    text: "круто, прекрасно",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Панч (от англ. punch – удар кулаком)",
    text:
      "изначально в рэпе (особенно в баттлах) колкая фраза, нацеленная на оппонента. Сейчас – словесный выпад, убойный аргумент. Так же в сфере спортивных единоборств удар",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Подсос",
    text:
      "Человек соглашающийся с авторитетным мнением, но не поддерживающий эту точку зрения",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Пруф",
    text: "Доказательство",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Раффл",
    text: "Лотерея, конкурс репостов в социальных сетях",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Рофлить",
    text:
      "Смеяться. От английской аббревиатуры ROFL – Rolling On the Floor Laughing – кататься по полу от смеха",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Сигна (иногда сайна, от англ. signature – подпись)",
    text:
      "Фотография с надписью на теле (чаще женском) или на бумаге с именем или ником",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Сижка (сига)",
    text: "Сигарета",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Стафф",
    text: "Произведение рэпера (композиция, альбом). Также марихуана",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Стримить",
    text:
      "Транслировать в прямом эфире собственную игру (у геймеров), либо другой аудиовизуальный контент",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Тащить",
    text: "Выполнять ключевую роль в какой-либо командной работе",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Флейм",
    text:
      "Словесная война в интернете, зачастую с применением взаимных оскорблений",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Форсить",
    text: "Активно пропагандировать или навязывать что-либо",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Хайп",
    text: "Шумиха",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Хейтить",
    text: "Выражать ненависть. Хейтер – тот, кто выражает ненависть, критикует",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Чилить",
    text: "Отдыхать, ничего не делая. Иногда тусоваться",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Шеймить",
    text:
      "критиковать, осуждать поведение в Сети. Наиболее известные формы – слатшейминг (обвинения в распущенности, аналог нашего уята), бодишейминг (критика людей, которые подчеркивают свою не самую подтянутую фигуру) и т. д.",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Эпик",
    text: "Нечто невообразимо крутое или величественное",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
  {
    title: "Я ору",
    text:
      "Фраза, выражающая крайне эмоциональную реакцию на что-либо, чаще всего на что-то, вызывающее смех",
    createdAt: Date.now(),
    cursor: `${Math.floor(Math.random() * Math.floor(Math.random() * Date.now()))}`,
    username: "andrew",
  },
];
